### PR TITLE
Updating the url to use https and version bump.

### PR DESCRIPTION
**Pull request by robbiethegeek**

### CODE REVIEW

**Comment by robbiethegeek** [comment]
@EvanLovely @illepic @smerrill can you guys take a look / merge.  Seems like there is an issue with defaulting to ssh and having no credentials within docker containers initially.  @smerrill and I looked at this on Saturday at the Drupal NYC Playday

**Comment by robbiethegeek** [comment]
bump...

**Comment by EvanLovely** [comment]
@robbiethegeek I merged this in and closed out the other bad PR #11. Thanks for getting this in! Was curious if the [GitHub shorthand in package.json](https://docs.npmjs.com/files/package.json#github-urls) could work here and might of provided the sensible defaults:

``` json
"dependencies": {
  "workshopper-jlord": "jlord/workshopper"
}
```

Anyway, I tested before merging with no errors (as I have ssh setup and GitHub creds), so I'm not able to test this fix; mind checking? Thanks! 🍻

**Comment by robbiethegeek** [comment]
@EvanLovely I was able to reproduce the error by trying to install from within a newly created docker container without passing through my ssh keys. It might work would you like to me to test or are you ok with this for now?

**Comment by EvanLovely** [comment]
@robbiethegeek ok, check this out again. See above commits.

**Comment by robbiethegeek** [comment]
👍 LGTM

**Comment by EvanLovely** [comment]
Awesome!

**Pull request merged**
